# Generated by Django 3.2 on 2021-04-15 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, verbose_name='amount')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('reference', models.CharField(max_length=255, verbose_name='reference')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('provider', models.CharField(choices=[('mtn', 'Mtn'), ('vod', 'Vodafone'), ('tgo', 'Airteltigo')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
