# Generated by Django 3.2 on 2021-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='amount',
            field=models.CharField(max_length=255, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='provider',
            field=models.CharField(choices=[('mtn', 'Mtn'), ('vod', 'Vodafone'), ('tgo', 'Airteltigo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='reference',
            field=models.CharField(max_length=255, verbose_name='Reference'),
        ),
    ]
