# Generated by Django 3.2 on 2021-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210415_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='callback_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Callback Url'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='reference',
            field=models.CharField(max_length=255, unique=True, verbose_name='Reference'),
        ),
    ]
