# Generated by Django 3.2 on 2021-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210415_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='reference',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Reference'),
        ),
    ]
