# Generated by Django 3.2 on 2021-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userrequest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
