# Generated by Django 3.2 on 2021-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userrequest_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='callback_url',
            field=models.CharField(default=None, max_length=255, verbose_name='Callback Url'),
        ),
    ]
