# Generated by Django 3.2 on 2021-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transactionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionresponse',
            name='callback_status',
            field=models.CharField(max_length=255, null=True, verbose_name='Call Back Status'),
        ),
    ]
