# Generated by Django 3.2.7 on 2021-11-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transactionresponse_callback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionresponse',
            name='display_text',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Display Text'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='reference',
            field=models.CharField(max_length=255, unique=True, verbose_name='Reference'),
        ),
    ]
