apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: payment-api
          image: kwobia/payment-api:1.5
          ports:
            - containerPort: 8990
          env:
            - name: POSTGRES_USER
              value: paymentuser
            - name: POSTGRES_SERVER
              value: payment-postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: paymentdb
            - name: POSTGRES_PASSWORD
              value: payment
            - name: PAYSTACK_API
              value: https://api.paystack.co/charge
            - name: PAYSTACK_SECRET_KEY_LIVE
              valueFrom:
                secretKeyRef:
                  name: paystack-credentials
                   key: PAYSTACK_SECRET_KEY_LIVE
            - name: PAYSTACK_PUBLIC_KEY_LIVE
                valueFrom:
                  secretKeyRef:
                    name: paystack-credentials
                     key: PAYSTACK_PUBLIC_KEY_LIVE
            - name: PAYSTACK_SECRET_KEY_TEST
                valueFrom:
                  secretKeyRef:
                    name: paystack-credentials
                      key: PAYSTACK_SECRET_KEY_TEST
            - name: PAYSTACK_PUBLIC_KEY_TEST
                valueFrom:
                  secretKeyRef:
                    name: paystack-credentials
                      key: PAYSTACK_PUBLIC_KEY_TEST


