apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: payment-api
          image: kwobia/payment-api:1.6
          ports:
            - containerPort: 8990
          envFrom:
            - secretRef:
                name: api-backend-env



