kind: PersistentVolume
apiVersion: v1
metadata:
  name: payment-postgres-pv-volume
  namespace: payment-api
  labels:
    type: local
    app: payment-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/payment/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: payment-postgres-pv-claim
  labels:
    app: payment-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi