apiVersion: v1
kind: Service
metadata:
  name: payment-postgres-service
  namespace: payment-api
  labels:
    app: payment-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: payment-postgres