apiVersion: v1
kind: Service
metadata:
  name: payment-server-cluster-ip-service
  namespace: payment
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 8000
      targetPort: 8000
