apiVersion: v1
kind: Service
metadata:
  name: payment-server-cluster-ip-service
  namespace: payment-api
spec:
  type: NodePort
  selector:
    component: server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30868
