apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30867
  selector:
    app: payment-service
